language: rust
rust:
  - stable
  - beta
  - nightly
cache: cargo

sudo: false

# Reduce email flood
notifications:
  email:
    on_success: never

# Only check develop for now
branches:
  only:
    - develop

script:
  - cargo check
  - cargo test
