language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

cache: cargo
sudo: false

# Reduce email flood
notifications:
  email:
    on_success: never

# Only check develop for now
branches:
  only:
    - develop

before_install:
  - rustup component add clippy

script:
  - cargo check
  - cargo clippy
  - cargo test
